#!/usr/bin/env node
/**
 * Reads data/broadcasters.yaml + data/stations.yaml, writes the curated
 * subset to public/stations.json. Stations inherit fields from their
 * broadcaster (metadata key, country, homepage) unless they override.
 *
 * Only stations whose status is one of {working, stream-only, icy-only}
 * are emitted. Other statuses (investigate, fetcher-todo, not-public,
 * broken) are kept in the YAML as documentation but stay out of the
 * shipped catalog.
 *
 * Run via:   npm run catalog       (or implicit via `npm run build`)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const PUBLISHABLE = new Set(['working', 'stream-only', 'icy-only']);

function loadYaml(path) {
  const text = readFileSync(join(root, path), 'utf8');
  const parsed = parseYaml(text);
  if (parsed === null || parsed === undefined) {
    throw new Error(`${path}: empty or invalid YAML`);
  }
  return parsed;
}

function fail(msg) {
  console.error(`build-catalog: ${msg}`);
  process.exit(1);
}

const broadcasters = loadYaml('data/broadcasters.yaml');
const stations = loadYaml('data/stations.yaml');

if (!broadcasters || typeof broadcasters !== 'object') fail('broadcasters.yaml: not a map');
if (!Array.isArray(stations)) fail('stations.yaml: not a list');

// Validate referential integrity + required fields
const errors = [];
const seenIds = new Set();
for (const s of stations) {
  if (!s || typeof s !== 'object') {
    errors.push('station entry is not an object');
    continue;
  }
  if (!s.id) errors.push(`station missing id: ${JSON.stringify(s).slice(0, 80)}`);
  else if (seenIds.has(s.id)) errors.push(`duplicate station id: ${s.id}`);
  else seenIds.add(s.id);
  if (!s.name) errors.push(`${s.id}: missing name`);
  if (!s.streamUrl) errors.push(`${s.id}: missing streamUrl`);
  if (!s.status) errors.push(`${s.id}: missing status`);
  if (!s.broadcaster) errors.push(`${s.id}: missing broadcaster`);
  else if (!broadcasters[s.broadcaster]) {
    errors.push(`${s.id}: unknown broadcaster ${s.broadcaster}`);
  }
}
if (errors.length > 0) {
  for (const e of errors) console.error(`build-catalog: ${e}`);
  process.exit(1);
}

// Resolve inheritance + filter to publishable
const built = [];
const counts = { total: stations.length, byStatus: {}, published: 0 };
for (const s of stations) {
  counts.byStatus[s.status] = (counts.byStatus[s.status] ?? 0) + 1;
  if (!PUBLISHABLE.has(s.status)) continue;
  const b = broadcasters[s.broadcaster];
  built.push({
    id: s.id,
    name: s.name,
    streamUrl: s.streamUrl,
    homepage: s.homepage ?? b.homepage,
    country: s.country ?? b.country,
    tags: s.tags,
    favicon: s.favicon,
    bitrate: s.bitrate,
    codec: s.codec,
    metadata: s.metadata ?? b.metadata,
    metadataUrl: s.metadataUrl,
    geo: Array.isArray(s.geo) && s.geo.length === 2 ? s.geo : undefined,
    featured: s.featured === true ? true : undefined,
  });
}
counts.published = built.length;

const outPath = join(root, 'public/stations.json');
mkdirSync(dirname(outPath), { recursive: true });
const payload = {
  $schema: 'generated by tools/build-catalog.mjs from data/{broadcasters,stations}.yaml',
  stations: built,
};
writeFileSync(outPath, JSON.stringify(payload, null, 2) + '\n');

const summary = Object.entries(counts.byStatus)
  .map(([k, v]) => `${k}=${v}`)
  .join(', ');
console.log(
  `catalog: ${counts.published}/${counts.total} stations published → public/stations.json (${summary})`,
);
