export interface Station {
  id: string;
  name: string;
  /** Distinguishing short label within this station's brand family — the
   *  tail left after stripping the leading words it shares with siblings
   *  (`Radio Gong 96.3 - Top 50 Gong` → `Top 50`). Derived at build time by
   *  `tools/lib/station-short-name.mjs`, grouped by the family model's
   *  `COUNTRY|homepage-host` bucket (`tools/lib/station-family.mjs`), or set
   *  explicitly in `data/stations.yaml` (override wins; an empty string opts
   *  out). Absent when the station stands alone, is its family's shared
   *  prefix, or yields only codec/bitrate noise or a tail too long to caption.
   *
   *  Advisory: clients show it only in space-constrained UI (e.g. the iOS
   *  icon-grid caption) where the full `name` would truncate; otherwise they
   *  render `name`. Forward-compatible — clients that don't know the field
   *  ignore it. */
  shortName?: string;
  /** Source broadcaster key from data/broadcasters.yaml when known. */
  broadcaster?: string;
  streamUrl: string;
  /** Optional homepage URL for attribution / "more info" links */
  homepage?: string;
  /** Optional country code (ISO 3166-1 alpha-2) */
  country?: string;
  /** Optional comma-or-array tags from Radio Browser, e.g. ["jazz", "ambient"] */
  tags?: string[];
  /** Optional artwork URL */
  favicon?: string;
  /** Pre-sized favicon variants generated by `tools/build-favicon-variants.mjs`.
   *  Keys are pixel widths matched to the iOS app's display sizes
   *  (38pt@2x = 76, 64pt@2x = 128, 76pt@2x = 152). Values are immutable,
   *  content-hashed paths relative to the catalog root (e.g.
   *  `favicons/builtin-fm4-128-abc12345.webp`). Clients should pick the
   *  smallest variant >= the requested display size and fall back to the
   *  original `favicon` URL when no variant is present (custom user
   *  stations, build-time fetch failures). */
  favicons?: { 76?: string; 128?: string; 152?: string };
  /** Provenance label: where we *discovered* the favicon URL.
   *  Set by the logo-curation tools or backfilled via URL pattern
   *  matching. Common values:
   *   - `wiki`             — `tools/wiki-logos.mjs` (Wikimedia Commons)
   *   - `broadcaster-site` — `tools/scrape-logos.mjs` (scraped from the broadcaster homepage)
   *   - `broadcaster-api`  — image URL returned by a broadcaster metadata API
   *   - `radio-browser`    — picked up via `tools/auto-curate.mjs` from RB's favicon field
   *   - `broadcaster`      — bundled local PNG hand-curated from the broadcaster
   *   - `manual`           — explicitly set in YAML by hand
   *   - absent             → unknown / not yet backfilled
   *  Note: this is "where we got the URL from", not "where the bytes live". */
  faviconSource?: string;
  /** Explicit "this station's favicon should be empty in the published catalog".
   *  Set by `tools/flag-suspicious-favicons.mjs` when the upstream URL points at
   *  a free-image-hosting / fan-upload host (postimg.cc, ibb.co, gstatic image
   *  thumbnails, …). Without this flag, build-catalog.mjs would fall back to
   *  the Radio Browser favicon — which is where the sketchy URLs live. */
  faviconBlocked?: boolean;
  /** Kind of asset the favicon URL points at. Independent from `faviconSource`
   *   - `bundle` — local PNG in `public/stations/<id>.png`
   *   - `api`    — URL is a service endpoint (image-service, ?w= size param, …)
   *   - `cdn`    — static asset hosted on broadcaster/Wikipedia/RB upload CDN
   *   - `none`   — no favicon at all
   *  Derived heuristically at render time by default; YAML may override. */
  faviconSourceType?: 'bundle' | 'api' | 'cdn' | 'none';
  /** Upstream URL the favicon was originally retrieved from. Only meaningful
   *  when `favicon` is a bundled local PNG (e.g. `stations/grrif.png`) —
   *  the URL we'd re-scrape from if regenerating the asset. For remote
   *  favicons this is usually redundant with `favicon` itself and can be
   *  omitted. */
  faviconSourceUrl?: string;
  /** License/usage rights label for the favicon. Open string; common values:
   *   - `wikipedia`              — from Wikimedia Commons (typically CC-BY-SA)
   *   - `broadcaster`            — explicit broadcaster-owned asset for bundled use
   *   - `broadcaster-implicit`   — remote broadcaster-hosted asset, not redistributed
   *   - `cc-by`, `cc-by-sa`, `cc-by-nc`, `cc0`, `public-domain` — explicit licenses
   *   - `unknown`                — not yet researched
   *  Absent ≡ `unknown`. Tracked per-station so we can audit redistribution risk. */
  faviconLicense?: string;
  /** Bitrate in kbps when known (Radio Browser bitrate field) */
  bitrate?: number;
  /** Audio codec when known, e.g. "MP3", "AAC" (Radio Browser codec field) */
  codec?: string;
  /** Approximate listener count — derived from Radio Browser clickcount */
  listeners?: number;
  /** Display-only "FM" frequency. Real RB stations rarely have one, so we
   * derive a deterministic pseudo-frequency in the 87.5–108.0 MHz range
   * from the station id so the tuner-dial visualization always has a target. */
  frequency?: string;
  /** Optional key into the metadata-fetcher registry (src/builtins.ts).
   *  Built-in stations declare which fetcher to use ("grrif", "fm4", "br"). */
  metadata?: string;
  /** Optional per-station URL passed to the fetcher (some fetchers, e.g.
   *  the BR radioplayer.json reader, need to know which channel to query). */
  metadataUrl?: string;
  /** Optional [latitude, longitude] for map placement. Sourced from
   *  Radio Browser (geo_lat / geo_long); rounded to 4 decimal places
   *  (~10m precision, plenty for a station map). */
  geo?: [number, number];
  /** Curation status from data/stations.yaml. Only the three publishable
   *  values reach the runtime catalog (build-catalog filters the rest):
   *  - `working`     — full per-broadcaster fetcher: stream + ICY + cover
   *  - `icy-only`    — stream + ICY-over-fetch metadata, no broadcaster API
   *  - `stream-only` — stream confirmed, no metadata source
   *  Drives the row capability badges. Absent on RB long-tail / custom adds. */
  status?: 'working' | 'icy-only' | 'stream-only';
  /** ISO-3166 alpha-2 country codes where the stream is known to be
   *  reachable. Absent means "no known restriction" — the default and
   *  the case for the overwhelming majority of stations. When set, the
   *  UI dims the row with a "<Country> only" badge for users outside
   *  the allow-list, and the playback error path translates upstream
   *  401s into a friendly geo-restricted message rather than a generic
   *  stream-failed alert. Set by curation when a broadcaster geo-gates
   *  (typically a music-licensing constraint — SUISA, GEMA, etc.). */
  availableIn?: string[];
}

export type PlayerState = 'idle' | 'loading' | 'playing' | 'paused' | 'error';

export interface NowPlaying {
  station: Station;
  state: PlayerState;
  /** Best-effort current track title. Often unavailable on web. */
  trackTitle?: string;
  /** Result of iTunes Search verification for the current track:
   *  `true` if iTunes returned a match (so it's plausibly a real
   *  song), `false` if iTunes returned 0 results (typical for news
   *  IDs, program names, station jingles), and `undefined` while the
   *  lookup is in-flight or hasn't been attempted. Drives the
   *  music-service link visibility in the now-playing pane — we only
   *  surface Spotify / Apple Music / YT Music links when iTunes
   *  confirms the title resolves to something searchable. */
  trackVerified?: boolean;
  /** Optional cover-art URL for the current track (when the metadata
   *  source provides one — e.g. Grrif's covers.json). */
  coverUrl?: string;
  /** Optional show / program currently on this station — i.e. the
   *  parent broadcast that bundles the songs (e.g. "Morning Show"
   *  on FM4). Separate from per-track info because programs change
   *  every hour or two while tracks change every few minutes. */
  programName?: string;
  programSubtitle?: string;
  errorMessage?: string;
}

/** A single armed wake-to-radio setting. v1 supports one at a time and
 *  no recurrence — once it fires (or the user disarms it), the entry
 *  is cleared. Time is local 24h "HH:MM"; we resolve to the next
 *  occurrence in JS so the same value works whether the user arms it
 *  in the morning or at night. */
export interface WakeTo {
  /** "HH:MM" 24h, local time. */
  time: string;
  /** Station to switch to + fade up at fire time. */
  stationId: string;
  /** Persisted snapshot of the station so the wake works even if
   *  BUILTIN_STATIONS is still loading at fire time. */
  station: Station;
  /** Epoch ms when the alarm was armed — used to disambiguate "today"
   *  vs "tomorrow" when the user arms a time that's already passed. */
  armedAt: number;
}
